# Generated by Django 6.0.6 on 2026-06-15 01:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("rss", "RSS/Atom"), ("readwise", "Readwise Reader")],
                        max_length=16,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Digest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")], max_length=8
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("sent", "Sent")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "period_start", "period_end"),
                        name="uniq_digest_kind_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=512)),
                ("url", models.URLField(max_length=1024)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("author", models.CharField(blank=True, max_length=256)),
                ("raw_content", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("summary", models.TextField(blank=True)),
                ("summarised_at", models.DateTimeField(blank=True, null=True)),
                ("summarise_failed", models.BooleanField(default=False)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="briefing.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("narrative", models.TextField()),
                ("importance", models.IntegerField(default=0)),
                (
                    "digest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="briefing.digest",
                    ),
                ),
            ],
            options={
                "ordering": ["-importance"],
            },
        ),
        migrations.CreateModel(
            name="ThemeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_items",
                        to="briefing.item",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_items",
                        to="briefing.theme",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="item_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="uniq_source_external_id"
            ),
        ),
    ]
